In [1]:
import pandas as pd
import requests 
import sqlalchemy
import psycopg2
import json
import numpy as np

In [2]:
pd.set_option('display.max_columns', None)

In [3]:
pd.set_option('display.max_colwidth', None)

In [4]:
from sqlalchemy import create_engine
from sqlalchemy.engine import URL

# Conectar ao banco PostgreSQL usando SQLAlchemy
url = URL.create(
    drivername="postgresql+psycopg2",
    username="admin_pg",
    password="1nbr@ndsIB",
    host="192.168.50.102",
    port=5432,
    database="db_bi_ti"
)
# Criar a engine de conexão
engine = create_engine(url)
# Ler a tabela
df = pd.read_sql('SELECT * FROM f_chamados_verdanadesk', engine)
# Exibir o dataframe
df.head()

,id,requerente,titulo,status,tipo,origem_abertura,prioridade,categoria,categoria_completa,localizacao,nome_tecnico,grupo,tempo_chamado,data_criacao,ultima_atualizacao,tempo_atribuicao,tempo_solucao,data_solucao,data_fechamento,expirado,tempo_resposta
0,27299,marcos.alves@inbrands.com.br,Feria Fora Do Prazo,Em atendimento (atribuído),Requisição,Formcreator,Alta,Férias,Férias > Programação De Férias > Férias Fora Do Prazo,CD EMBU,NaN,Administração de Pessoal,Não atribuído,2026-05-13 09:45:14,2026-05-13 09:45:14,NaT,2026-05-15 16:45:14,Não atribuído,Não atribuído,No prazo,NaN
1,27298,joao.lima@inbrands.com.br,Exclusão De Horário,Em atendimento (atribuído),Requisição,Formcreator,Média,Ponto Eletrônico,Ponto Eletrônico > Manutenção De Ponto > Ajuste De Marcação,HUB-SP - CENESP BL C,NaN,Administração de Pessoal,Não atribuído,2026-05-13 09:35:22,2026-05-13 09:35:22,NaT,2026-05-20 13:35:22,Não atribuído,Não atribuído,No prazo,NaN
2,27297,haroldo.verli@inbrands.com.br,Rescisão Solicito Avaliação Para Desligamento Do Colaborador,Em atendimento (atribuído),Requisição,Formcreator,Média,Rescisão,Rescisão > Rescisão > Prévia De Rescisão,CD EMBU,Geovanna Lucena de Oliveira,Administração de Pessoal,Não atribuído,2026-05-13 09:26:53,2026-05-13 09:26:53,NaT,2026-05-20 13:26:53,Não atribuído,Não atribuído,No prazo,NaN
3,27296,haroldo.verli@inbrands.com.br,Rescisão Solicito Avaliação Para Desligamento Do Colaborador,Em atendimento (atribuído),Requisição,Formcreator,Média,Rescisão,Rescisão > Rescisão > Prévia De Rescisão,CD EMBU,Geovanna Lucena de Oliveira,Administração de Pessoal,Não atribuído,2026-05-13 09:25:12,2026-05-13 09:25:12,NaT,2026-05-20 13:25:12,Não atribuído,Não atribuído,No prazo,NaN
4,27295,haroldo.verli@inbrands.com.br,Rescisão Solicito Avaliação Para Desligamento Do Colaborador,Em atendimento (atribuído),Requisição,Formcreator,Média,Rescisão,Rescisão > Rescisão > Prévia De Rescisão,CD EMBU,Geovanna Lucena de Oliveira,Administração de Pessoal,Não atribuído,2026-05-13 09:20:24,2026-05-13 09:20:24,NaT,2026-05-20 13:20:24,Não atribuído,Não atribuído,No prazo,NaN

In [5]:
# Tratamaneto dos campos data

colunas_data = ['data_criacao', 'ultima_atualizacao', 'tempo_atribuicao', 'tempo_solucao', 'data_fechamento']
for col in colunas_data:
    df[col] = pd.to_datetime(df[col], errors='coerce', dayfirst=True, format='%d/%m/%Y %H:%M:%S').dt.strftime('%d/%m/%Y %H:%M:%S')

# Tratamento do campo titulo

df['titulo'] = df['titulo'].astype(str).str.upper()

df

,id,requerente,titulo,status,tipo,origem_abertura,prioridade,categoria,categoria_completa,localizacao,nome_tecnico,grupo,tempo_chamado,data_criacao,ultima_atualizacao,tempo_atribuicao,tempo_solucao,data_solucao,data_fechamento,expirado,tempo_resposta
0,27299,marcos.alves@inbrands.com.br,FERIA FORA DO PRAZO,Em atendimento (atribuído),Requisição,Formcreator,Alta,Férias,Férias > Programação De Férias > Férias Fora Do Prazo,CD EMBU,NaN,Administração de Pessoal,Não atribuído,NaN,NaN,NaN,NaN,Não atribuído,NaN,No prazo,NaN
1,27298,joao.lima@inbrands.com.br,EXCLUSÃO DE HORÁRIO,Em atendimento (atribuído),Requisição,Formcreator,Média,Ponto Eletrônico,Ponto Eletrônico > Manutenção De Ponto > Ajuste De Marcação,HUB-SP - CENESP BL C,NaN,Administração de Pessoal,Não atribuído,NaN,NaN,NaN,NaN,Não atribuído,NaN,No prazo,NaN
2,27297,haroldo.verli@inbrands.com.br,RESCISÃO SOLICITO AVALIAÇÃO PARA DESLIGAMENTO DO COLABORADOR,Em atendimento (atribuído),Requisição,Formcreator,Média,Rescisão,Rescisão > Rescisão > Prévia De Rescisão,CD EMBU,Geovanna Lucena de Oliveira,Administração de Pessoal,Não atribuído,NaN,NaN,NaN,NaN,Não atribuído,NaN,No prazo,NaN
3,27296,haroldo.verli@inbrands.com.br,RESCISÃO SOLICITO AVALIAÇÃO PARA DESLIGAMENTO DO COLABORADOR,Em atendimento (atribuído),Requisição,Formcreator,Média,Rescisão,Rescisão > Rescisão > Prévia De Rescisão,CD EMBU,Geovanna Lucena de Oliveira,Administração de Pessoal,Não atribuído,NaN,NaN,NaN,NaN,Não atribuído,NaN,No prazo,NaN
4,27295,haroldo.verli@inbrands.com.br,RESCISÃO SOLICITO AVALIAÇÃO PARA DESLIGAMENTO DO COLABORADOR,Em atendimento (atribuído),Requisição,Formcreator,Média,Rescisão,Rescisão > Rescisão > Prévia De Rescisão,CD EMBU,Geovanna Lucena de Oliveira,Administração de Pessoal,Não atribuído,NaN,NaN,NaN,NaN,Não atribuído,NaN,No prazo,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
26741,71,salinas.higienopolis@inbrands.com.br,NOTAS FISCAIS NÃO APARECEM PARA ENTRADA.,Fechado,Requisição,Formcreator,Baixa,Fiscal,Fiscal > Reprocessamento De Notas Fiscais,LOJAS,Thaina Carvalho do Nascimento,TI | Suporte a Lojas,Não atribuído,NaN,NaN,NaN,NaN,2025-04-08 18:59:35,NaN,Vencido,02:00
26742,70,salinas.higienopolis@inbrands.com.br,NOTA FISCAL DE DOAÇÃO,Fechado,Requisição,Formcreator,Baixa,Fiscal,Fiscal > Reprocessamento De Notas Fiscais,LOJAS,Thaina Carvalho do Nascimento,TI | Suporte a Lojas,Não atribuído,NaN,NaN,NaN,NaN,2025-04-08 18:58:27,NaN,Vencido,02:00
26743,69,salinas.iguatemi@inbrands.com.br,PEÇA NÃO CADASTRADA,Fechado,Requisição,Formcreator,Muito baixa,Não Atribuído,Não Atribuído,LOJAS,Thaina Carvalho do Nascimento,TI | Suporte a Lojas,Não atribuído,NaN,NaN,NaN,NaN,2025-04-10 18:41:44,NaN,Vencido,03:00
26744,68,gerente.s27@inbrands.com.br,ESTOU PRECISANDO PASSAR VENDA NO LINXPOS E A TELA DE VENDAS NÃO ESTÁ ABRINDO. PAROU DE FUNCIONAR HOJE A TARDE DEPOIS DE UMA ATUALIZAÇÃO FEIRA POR AÍ MESMO.,Fechado,Incidente,Chat,Média,Linxpos Manager,Linxpos Manager > Linxpos Manager Não Abre,SL27 - OSCAR FREIRE,Gabriel Mariano,TI | Suporte a Lojas,00:00:00,NaN,NaN,NaN,NaN,2025-04-08 09:33:41,NaN,Não atribuído,NaN
26745,67,gerente.s27@inbrands.com.br,LINXPOS NÃO ESTÁ PASSANDO VENDA,Fechado,Incidente,Formcreator,Alta,Linxpos,Linxpos > Erro Ao Finalizar Venda,SL27 - OSCAR FREIRE,Gabriel Mariano,TI | Suporte a Lojas,Não atribuído,NaN,NaN,NaN,NaN,2025-04-08 09:31:10,NaN,Vencido,00:30

In [6]:
df.columns = df.columns.str.strip()
df.columns

Index(['id', 'requerente', 'titulo', 'status', 'tipo', 'origem_abertura',
       'prioridade', 'categoria', 'categoria_completa', 'localizacao',
       'nome_tecnico', 'grupo', 'tempo_chamado', 'data_criacao',
       'ultima_atualizacao', 'tempo_atribuicao', 'tempo_solucao',
       'data_solucao', 'data_fechamento', 'expirado', 'tempo_resposta'],
      dtype='str')

In [7]:
df = df.replace(pd.NaT, "")

# Tratamento do campo Categoria
df['categoria'] = df['categoria'].astype(str)

df[['categoria', 'subcategoria']] = (
    df['categoria_completa']
    .str.split('>', n=1, expand=True)
)

# Remover espaços extras e dados nulos
df['categoria'] = df['categoria'].str.strip()
df['subcategoria'] = df['subcategoria'].str.strip().fillna('Não atribuído')

df

,id,requerente,titulo,status,tipo,origem_abertura,prioridade,categoria,categoria_completa,localizacao,nome_tecnico,grupo,tempo_chamado,data_criacao,ultima_atualizacao,tempo_atribuicao,tempo_solucao,data_solucao,data_fechamento,expirado,tempo_resposta,subcategoria
0,27299,marcos.alves@inbrands.com.br,FERIA FORA DO PRAZO,Em atendimento (atribuído),Requisição,Formcreator,Alta,Férias,Férias > Programação De Férias > Férias Fora Do Prazo,CD EMBU,,Administração de Pessoal,Não atribuído,,,,,Não atribuído,,No prazo,,Programação De Férias > Férias Fora Do Prazo
1,27298,joao.lima@inbrands.com.br,EXCLUSÃO DE HORÁRIO,Em atendimento (atribuído),Requisição,Formcreator,Média,Ponto Eletrônico,Ponto Eletrônico > Manutenção De Ponto > Ajuste De Marcação,HUB-SP - CENESP BL C,,Administração de Pessoal,Não atribuído,,,,,Não atribuído,,No prazo,,Manutenção De Ponto > Ajuste De Marcação
2,27297,haroldo.verli@inbrands.com.br,RESCISÃO SOLICITO AVALIAÇÃO PARA DESLIGAMENTO DO COLABORADOR,Em atendimento (atribuído),Requisição,Formcreator,Média,Rescisão,Rescisão > Rescisão > Prévia De Rescisão,CD EMBU,Geovanna Lucena de Oliveira,Administração de Pessoal,Não atribuído,,,,,Não atribuído,,No prazo,,Rescisão > Prévia De Rescisão
3,27296,haroldo.verli@inbrands.com.br,RESCISÃO SOLICITO AVALIAÇÃO PARA DESLIGAMENTO DO COLABORADOR,Em atendimento (atribuído),Requisição,Formcreator,Média,Rescisão,Rescisão > Rescisão > Prévia De Rescisão,CD EMBU,Geovanna Lucena de Oliveira,Administração de Pessoal,Não atribuído,,,,,Não atribuído,,No prazo,,Rescisão > Prévia De Rescisão
4,27295,haroldo.verli@inbrands.com.br,RESCISÃO SOLICITO AVALIAÇÃO PARA DESLIGAMENTO DO COLABORADOR,Em atendimento (atribuído),Requisição,Formcreator,Média,Rescisão,Rescisão > Rescisão > Prévia De Rescisão,CD EMBU,Geovanna Lucena de Oliveira,Administração de Pessoal,Não atribuído,,,,,Não atribuído,,No prazo,,Rescisão > Prévia De Rescisão
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
26741,71,salinas.higienopolis@inbrands.com.br,NOTAS FISCAIS NÃO APARECEM PARA ENTRADA.,Fechado,Requisição,Formcreator,Baixa,Fiscal,Fiscal > Reprocessamento De Notas Fiscais,LOJAS,Thaina Carvalho do Nascimento,TI | Suporte a Lojas,Não atribuído,,,,,2025-04-08 18:59:35,,Vencido,02:00,Reprocessamento De Notas Fiscais
26742,70,salinas.higienopolis@inbrands.com.br,NOTA FISCAL DE DOAÇÃO,Fechado,Requisição,Formcreator,Baixa,Fiscal,Fiscal > Reprocessamento De Notas Fiscais,LOJAS,Thaina Carvalho do Nascimento,TI | Suporte a Lojas,Não atribuído,,,,,2025-04-08 18:58:27,,Vencido,02:00,Reprocessamento De Notas Fiscais
26743,69,salinas.iguatemi@inbrands.com.br,PEÇA NÃO CADASTRADA,Fechado,Requisição,Formcreator,Muito baixa,Não Atribuído,Não Atribuído,LOJAS,Thaina Carvalho do Nascimento,TI | Suporte a Lojas,Não atribuído,,,,,2025-04-10 18:41:44,,Vencido,03:00,Não atribuído
26744,68,gerente.s27@inbrands.com.br,ESTOU PRECISANDO PASSAR VENDA NO LINXPOS E A TELA DE VENDAS NÃO ESTÁ ABRINDO. PAROU DE FUNCIONAR HOJE A TARDE DEPOIS DE UMA ATUALIZAÇÃO FEIRA POR AÍ MESMO.,Fechado,Incidente,Chat,Média,Linxpos Manager,Linxpos Manager > Linxpos Manager Não Abre,SL27 - OSCAR FREIRE,Gabriel Mariano,TI | Suporte a Lojas,00:00:00,,,,,2025-04-08 09:33:41,,Não atribuído,,Linxpos Manager Não Abre
26745,67,gerente.s27@inbrands.com.br,LINXPOS NÃO ESTÁ PASSANDO VENDA,Fechado,Incidente,Formcreator,Alta,Linxpos,Linxpos > Erro Ao Finalizar Venda,SL27 - OSCAR FREIRE,Gabriel Mariano,TI | Suporte a Lojas,Não atribuído,,,,,2025-04-08 09:31:10,,Vencido,00:30,Erro Ao Finalizar Venda

In [8]:
# Tratamento do campo nome tecnico e grupo

df['nome_tecnico'] = df['nome_tecnico'].astype(str)
df['grupo'] = df['grupo'].astype(str)


df[['departamento', 'grupo_descricao']] = (
    df['grupo']
    .str.split('|', n=1, expand=True)
)

df['nome_tecnico'] = df['nome_tecnico'].str.strip()
df['departamento'] = df['departamento'].str.strip()
df['grupo_descricao'] = df['grupo_descricao'].str.strip()

df

,id,requerente,titulo,status,tipo,origem_abertura,prioridade,categoria,categoria_completa,localizacao,nome_tecnico,grupo,tempo_chamado,data_criacao,ultima_atualizacao,tempo_atribuicao,tempo_solucao,data_solucao,data_fechamento,expirado,tempo_resposta,subcategoria,departamento,grupo_descricao
0,27299,marcos.alves@inbrands.com.br,FERIA FORA DO PRAZO,Em atendimento (atribuído),Requisição,Formcreator,Alta,Férias,Férias > Programação De Férias > Férias Fora Do Prazo,CD EMBU,,Administração de Pessoal,Não atribuído,,,,,Não atribuído,,No prazo,,Programação De Férias > Férias Fora Do Prazo,Administração de Pessoal,NaN
1,27298,joao.lima@inbrands.com.br,EXCLUSÃO DE HORÁRIO,Em atendimento (atribuído),Requisição,Formcreator,Média,Ponto Eletrônico,Ponto Eletrônico > Manutenção De Ponto > Ajuste De Marcação,HUB-SP - CENESP BL C,,Administração de Pessoal,Não atribuído,,,,,Não atribuído,,No prazo,,Manutenção De Ponto > Ajuste De Marcação,Administração de Pessoal,NaN
2,27297,haroldo.verli@inbrands.com.br,RESCISÃO SOLICITO AVALIAÇÃO PARA DESLIGAMENTO DO COLABORADOR,Em atendimento (atribuído),Requisição,Formcreator,Média,Rescisão,Rescisão > Rescisão > Prévia De Rescisão,CD EMBU,Geovanna Lucena de Oliveira,Administração de Pessoal,Não atribuído,,,,,Não atribuído,,No prazo,,Rescisão > Prévia De Rescisão,Administração de Pessoal,NaN
3,27296,haroldo.verli@inbrands.com.br,RESCISÃO SOLICITO AVALIAÇÃO PARA DESLIGAMENTO DO COLABORADOR,Em atendimento (atribuído),Requisição,Formcreator,Média,Rescisão,Rescisão > Rescisão > Prévia De Rescisão,CD EMBU,Geovanna Lucena de Oliveira,Administração de Pessoal,Não atribuído,,,,,Não atribuído,,No prazo,,Rescisão > Prévia De Rescisão,Administração de Pessoal,NaN
4,27295,haroldo.verli@inbrands.com.br,RESCISÃO SOLICITO AVALIAÇÃO PARA DESLIGAMENTO DO COLABORADOR,Em atendimento (atribuído),Requisição,Formcreator,Média,Rescisão,Rescisão > Rescisão > Prévia De Rescisão,CD EMBU,Geovanna Lucena de Oliveira,Administração de Pessoal,Não atribuído,,,,,Não atribuído,,No prazo,,Rescisão > Prévia De Rescisão,Administração de Pessoal,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
26741,71,salinas.higienopolis@inbrands.com.br,NOTAS FISCAIS NÃO APARECEM PARA ENTRADA.,Fechado,Requisição,Formcreator,Baixa,Fiscal,Fiscal > Reprocessamento De Notas Fiscais,LOJAS,Thaina Carvalho do Nascimento,TI | Suporte a Lojas,Não atribuído,,,,,2025-04-08 18:59:35,,Vencido,02:00,Reprocessamento De Notas Fiscais,TI,Suporte a Lojas
26742,70,salinas.higienopolis@inbrands.com.br,NOTA FISCAL DE DOAÇÃO,Fechado,Requisição,Formcreator,Baixa,Fiscal,Fiscal > Reprocessamento De Notas Fiscais,LOJAS,Thaina Carvalho do Nascimento,TI | Suporte a Lojas,Não atribuído,,,,,2025-04-08 18:58:27,,Vencido,02:00,Reprocessamento De Notas Fiscais,TI,Suporte a Lojas
26743,69,salinas.iguatemi@inbrands.com.br,PEÇA NÃO CADASTRADA,Fechado,Requisição,Formcreator,Muito baixa,Não Atribuído,Não Atribuído,LOJAS,Thaina Carvalho do Nascimento,TI | Suporte a Lojas,Não atribuído,,,,,2025-04-10 18:41:44,,Vencido,03:00,Não atribuído,TI,Suporte a Lojas
26744,68,gerente.s27@inbrands.com.br,ESTOU PRECISANDO PASSAR VENDA NO LINXPOS E A TELA DE VENDAS NÃO ESTÁ ABRINDO. PAROU DE FUNCIONAR HOJE A TARDE DEPOIS DE UMA ATUALIZAÇÃO FEIRA POR AÍ MESMO.,Fechado,Incidente,Chat,Média,Linxpos Manager,Linxpos Manager > Linxpos Manager Não Abre,SL27 - OSCAR FREIRE,Gabriel Mariano,TI | Suporte a Lojas,00:00:00,,,,,2025-04-08 09:33:41,,Não atribuído,,Linxpos Manager Não Abre,TI,Suporte a Lojas
26745,67,gerente.s27@inbrands.com.br,LINXPOS NÃO ESTÁ PASSANDO VENDA,Fechado,Incidente,Formcreator,Alta,Linxpos,Linxpos > Erro Ao Finalizar Venda,SL27 - OSCAR FREIRE,Gabriel Mariano,TI | Suporte a Lojas,Não atribuído,,,,,2025-04-08 09:31:10,,Vencido,00:30,Erro Ao Finalizar Venda,TI,Suporte a Lojas

In [33]:
# Criando a coluna de Status_macro

df['status'] = (df['status'].astype(str)
                .str.upper()
                .str.strip()
                )

map_status_macro = {'NOVO': 'Aberto',
                    'EM ATENDIMENTO (ATRIBUÍDO)': 'Em atendimento', 
                    'EM ATENDIMENTO (PLANEJADO)': 'Em atendimento',
                    'FECHADO': 'Fechado',
                    'SOLUCIONADO': 'Fechado',
                    'PENDENTE': 'Pendente',
                    }

df['status_macro'] = (df['status'].map(map_status_macro))

df

,id,email_requerente,titulo,status,tipo,origem_abertura,prioridade,categoria,categoria_completa,localizacao,nome_tecnico,grupo,tempo_chamado,data_criacao,ultima_atualizacao,tempo_atribuicao,tempo_solucao,data_solucao,data_fechamento,expirado,tempo_resposta,subcategoria,departamento,grupo_descricao,status_macro,flag_sem_tecnico,dominio_email
0,27299,marcos.alves@inbrands.com.br,FERIA FORA DO PRAZO,EM ATENDIMENTO (ATRIBUÍDO),Requisição,Formcreator,Alta,Férias,Férias > Programação De Férias > Férias Fora Do Prazo,CD EMBU,,Administração de Pessoal,Não atribuído,,,,,Não atribuído,,No prazo,,Programação De Férias > Férias Fora Do Prazo,Administração de Pessoal,NaN,Em atendimento,0,inbrands.com.br
1,27298,joao.lima@inbrands.com.br,EXCLUSÃO DE HORÁRIO,EM ATENDIMENTO (ATRIBUÍDO),Requisição,Formcreator,Média,Ponto Eletrônico,Ponto Eletrônico > Manutenção De Ponto > Ajuste De Marcação,HUB-SP - CENESP BL C,,Administração de Pessoal,Não atribuído,,,,,Não atribuído,,No prazo,,Manutenção De Ponto > Ajuste De Marcação,Administração de Pessoal,NaN,Em atendimento,0,inbrands.com.br
2,27297,haroldo.verli@inbrands.com.br,RESCISÃO SOLICITO AVALIAÇÃO PARA DESLIGAMENTO DO COLABORADOR,EM ATENDIMENTO (ATRIBUÍDO),Requisição,Formcreator,Média,Rescisão,Rescisão > Rescisão > Prévia De Rescisão,CD EMBU,Geovanna Lucena de Oliveira,Administração de Pessoal,Não atribuído,,,,,Não atribuído,,No prazo,,Rescisão > Prévia De Rescisão,Administração de Pessoal,NaN,Em atendimento,0,inbrands.com.br
3,27296,haroldo.verli@inbrands.com.br,RESCISÃO SOLICITO AVALIAÇÃO PARA DESLIGAMENTO DO COLABORADOR,EM ATENDIMENTO (ATRIBUÍDO),Requisição,Formcreator,Média,Rescisão,Rescisão > Rescisão > Prévia De Rescisão,CD EMBU,Geovanna Lucena de Oliveira,Administração de Pessoal,Não atribuído,,,,,Não atribuído,,No prazo,,Rescisão > Prévia De Rescisão,Administração de Pessoal,NaN,Em atendimento,0,inbrands.com.br
4,27295,haroldo.verli@inbrands.com.br,RESCISÃO SOLICITO AVALIAÇÃO PARA DESLIGAMENTO DO COLABORADOR,EM ATENDIMENTO (ATRIBUÍDO),Requisição,Formcreator,Média,Rescisão,Rescisão > Rescisão > Prévia De Rescisão,CD EMBU,Geovanna Lucena de Oliveira,Administração de Pessoal,Não atribuído,,,,,Não atribuído,,No prazo,,Rescisão > Prévia De Rescisão,Administração de Pessoal,NaN,Em atendimento,0,inbrands.com.br
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
26741,71,salinas.higienopolis@inbrands.com.br,NOTAS FISCAIS NÃO APARECEM PARA ENTRADA.,FECHADO,Requisição,Formcreator,Baixa,Fiscal,Fiscal > Reprocessamento De Notas Fiscais,LOJAS,Thaina Carvalho do Nascimento,TI | Suporte a Lojas,Não atribuído,,,,,2025-04-08 18:59:35,,Vencido,02:00,Reprocessamento De Notas Fiscais,TI,Suporte a Lojas,Fechado,0,inbrands.com.br
26742,70,salinas.higienopolis@inbrands.com.br,NOTA FISCAL DE DOAÇÃO,FECHADO,Requisição,Formcreator,Baixa,Fiscal,Fiscal > Reprocessamento De Notas Fiscais,LOJAS,Thaina Carvalho do Nascimento,TI | Suporte a Lojas,Não atribuído,,,,,2025-04-08 18:58:27,,Vencido,02:00,Reprocessamento De Notas Fiscais,TI,Suporte a Lojas,Fechado,0,inbrands.com.br
26743,69,salinas.iguatemi@inbrands.com.br,PEÇA NÃO CADASTRADA,FECHADO,Requisição,Formcreator,Muito baixa,Não Atribuído,Não Atribuído,LOJAS,Thaina Carvalho do Nascimento,TI | Suporte a Lojas,Não atribuído,,,,,2025-04-10 18:41:44,,Vencido,03:00,Não atribuído,TI,Suporte a Lojas,Fechado,0,inbrands.com.br
26744,68,gerente.s27@inbrands.com.br,ESTOU PRECISANDO PASSAR VENDA NO LINXPOS E A TELA DE VENDAS NÃO ESTÁ ABRINDO. PAROU DE FUNCIONAR HOJE A TARDE DEPOIS DE UMA ATUALIZAÇÃO FEIRA POR AÍ MESMO.,FECHADO,Incidente,Chat,Média,Linxpos Manager,Linxpos Manager > Linxpos Manager Não Abre,SL27 - OSCAR FREIRE,Gabriel Mariano,TI | Suporte a Lojas,00:00:00,,,,,2025-04-08 09:33:41,,Não atribuído,,Linxpos Manager Não Abre,TI,Suporte a Lojas,Fechado,0,inbrands.com.br
26745,67,gerente.s27@inbrands.com.br,LINXPOS NÃO ESTÁ PASSANDO VENDA,FECHADO,Incidente,Formcreator,Alta,Linxpos,Linxpos > Erro Ao Finalizar Venda,SL27 - OSCAR FREIRE,Gabriel Mariano,TI | Suporte a Lojas,Não atribuído,,,,,2025-04-08 09:31:10,,Vencido,00:30,Erro Ao Finalizar Venda,TI,Suporte a Lojas,Fechado,0,inbrands.com.br

In [34]:
# Criando a Tabela Dimensão do Status do Chamado

D_STATUS = (
    df[['status', 'status_macro']]
    .drop_duplicates()
    .sort_values(by='status')
    .reset_index(drop=True)
)
D_STATUS['status_sk'] = D_STATUS.index + 1
D_STATUS

                       status    status_macro  status_sk
0  EM ATENDIMENTO (ATRIBUÍDO)  Em atendimento          1
1  EM ATENDIMENTO (PLANEJADO)  Em atendimento          2
2                     FECHADO         Fechado          3
3                        NOVO          Aberto          4
4                    PENDENTE        Pendente          5
5                 SOLUCIONADO         Fechado          6

In [35]:
# Criando a Tabela Dimensão referente ao Tecnico do chamado

D_TECNICO = (
    df[['nome_tecnico','departamento']]
    .drop_duplicates()
    .sort_values(by='nome_tecnico')
    .reset_index(drop=True)
)

df['flag_sem_tecnico'] = np.where(df['nome_tecnico'].isnull(), 1, 0)
if df['flag_sem_tecnico'].sum() > 1:
    print("Sem Técnico")
df_com_tecnico = df[df['flag_sem_tecnico'] == 0]

D_TECNICO['tecnico_sk'] = D_TECNICO.index + 1
D_TECNICO

,nome_tecnico,departamento,tecnico_sk
0,,Administração de Pessoal,1
1,,CROWN IT - Atualização de Versão Linx,2
2,,GPP / Segurança (HUB),3
3,,TI,4
4,,Remuneração,5
...,...,...,...
62,Valdir Bosco da Silva Junior,TI,63
63,Vanusa Pereira Sales,Administração de Pessoal,64
64,Weslley de Santana Moreira,TI,65
65,Weslley de Santana Moreira,CROWN IT N2,66
66,Yuri Santos,TI,67

In [36]:
# Criando a tabela dimensão da categoria do chamado
D_CATEGORIA = (
    df[['categoria', 'subcategoria']]
    .drop_duplicates()
    .sort_values(by='categoria')
    .reset_index(drop=True)
)
D_CATEGORIA['categoria_sk'] = D_CATEGORIA.index + 1
D_CATEGORIA

                      categoria                 subcategoria  categoria_sk
0    Abertura Via Chat Indevida                Não atribuído             1
1                       Acessos                         Site             2
2                       Acessos                        Wi-Fi             3
3                       Acessos               Banco De Dados             4
4                       Acessos  Liberação De Pastas Da Rede             5
..                          ...                          ...           ...
512                 Verdanadesk  Criação De Filtros / Regras           513
513                 Verdanadesk                       Perfil           514
514                 Verdanadesk                      Ajustes           515
515                 Verdanadesk         Criação De Categoria           516
516   Vidros E Espelhos - Lojas    Vidro Ou Espelho Quebrado           517

[517 rows x 3 columns]

In [37]:
# Criando os campos email_requerente e dominio_email
df = df.rename(columns={'requerente': 'email_requerente'})
df['dominio_email'] = df['email_requerente'].str.split('@').str[1]
df['dominio_email'] = df['dominio_email'].fillna('Não atribuído')
df

,id,email_requerente,titulo,status,tipo,origem_abertura,prioridade,categoria,categoria_completa,localizacao,nome_tecnico,grupo,tempo_chamado,data_criacao,ultima_atualizacao,tempo_atribuicao,tempo_solucao,data_solucao,data_fechamento,expirado,tempo_resposta,subcategoria,departamento,grupo_descricao,status_macro,flag_sem_tecnico,dominio_email
0,27299,marcos.alves@inbrands.com.br,FERIA FORA DO PRAZO,EM ATENDIMENTO (ATRIBUÍDO),Requisição,Formcreator,Alta,Férias,Férias > Programação De Férias > Férias Fora Do Prazo,CD EMBU,,Administração de Pessoal,Não atribuído,,,,,Não atribuído,,No prazo,,Programação De Férias > Férias Fora Do Prazo,Administração de Pessoal,NaN,Em atendimento,0,inbrands.com.br
1,27298,joao.lima@inbrands.com.br,EXCLUSÃO DE HORÁRIO,EM ATENDIMENTO (ATRIBUÍDO),Requisição,Formcreator,Média,Ponto Eletrônico,Ponto Eletrônico > Manutenção De Ponto > Ajuste De Marcação,HUB-SP - CENESP BL C,,Administração de Pessoal,Não atribuído,,,,,Não atribuído,,No prazo,,Manutenção De Ponto > Ajuste De Marcação,Administração de Pessoal,NaN,Em atendimento,0,inbrands.com.br
2,27297,haroldo.verli@inbrands.com.br,RESCISÃO SOLICITO AVALIAÇÃO PARA DESLIGAMENTO DO COLABORADOR,EM ATENDIMENTO (ATRIBUÍDO),Requisição,Formcreator,Média,Rescisão,Rescisão > Rescisão > Prévia De Rescisão,CD EMBU,Geovanna Lucena de Oliveira,Administração de Pessoal,Não atribuído,,,,,Não atribuído,,No prazo,,Rescisão > Prévia De Rescisão,Administração de Pessoal,NaN,Em atendimento,0,inbrands.com.br
3,27296,haroldo.verli@inbrands.com.br,RESCISÃO SOLICITO AVALIAÇÃO PARA DESLIGAMENTO DO COLABORADOR,EM ATENDIMENTO (ATRIBUÍDO),Requisição,Formcreator,Média,Rescisão,Rescisão > Rescisão > Prévia De Rescisão,CD EMBU,Geovanna Lucena de Oliveira,Administração de Pessoal,Não atribuído,,,,,Não atribuído,,No prazo,,Rescisão > Prévia De Rescisão,Administração de Pessoal,NaN,Em atendimento,0,inbrands.com.br
4,27295,haroldo.verli@inbrands.com.br,RESCISÃO SOLICITO AVALIAÇÃO PARA DESLIGAMENTO DO COLABORADOR,EM ATENDIMENTO (ATRIBUÍDO),Requisição,Formcreator,Média,Rescisão,Rescisão > Rescisão > Prévia De Rescisão,CD EMBU,Geovanna Lucena de Oliveira,Administração de Pessoal,Não atribuído,,,,,Não atribuído,,No prazo,,Rescisão > Prévia De Rescisão,Administração de Pessoal,NaN,Em atendimento,0,inbrands.com.br
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
26741,71,salinas.higienopolis@inbrands.com.br,NOTAS FISCAIS NÃO APARECEM PARA ENTRADA.,FECHADO,Requisição,Formcreator,Baixa,Fiscal,Fiscal > Reprocessamento De Notas Fiscais,LOJAS,Thaina Carvalho do Nascimento,TI | Suporte a Lojas,Não atribuído,,,,,2025-04-08 18:59:35,,Vencido,02:00,Reprocessamento De Notas Fiscais,TI,Suporte a Lojas,Fechado,0,inbrands.com.br
26742,70,salinas.higienopolis@inbrands.com.br,NOTA FISCAL DE DOAÇÃO,FECHADO,Requisição,Formcreator,Baixa,Fiscal,Fiscal > Reprocessamento De Notas Fiscais,LOJAS,Thaina Carvalho do Nascimento,TI | Suporte a Lojas,Não atribuído,,,,,2025-04-08 18:58:27,,Vencido,02:00,Reprocessamento De Notas Fiscais,TI,Suporte a Lojas,Fechado,0,inbrands.com.br
26743,69,salinas.iguatemi@inbrands.com.br,PEÇA NÃO CADASTRADA,FECHADO,Requisição,Formcreator,Muito baixa,Não Atribuído,Não Atribuído,LOJAS,Thaina Carvalho do Nascimento,TI | Suporte a Lojas,Não atribuído,,,,,2025-04-10 18:41:44,,Vencido,03:00,Não atribuído,TI,Suporte a Lojas,Fechado,0,inbrands.com.br
26744,68,gerente.s27@inbrands.com.br,ESTOU PRECISANDO PASSAR VENDA NO LINXPOS E A TELA DE VENDAS NÃO ESTÁ ABRINDO. PAROU DE FUNCIONAR HOJE A TARDE DEPOIS DE UMA ATUALIZAÇÃO FEIRA POR AÍ MESMO.,FECHADO,Incidente,Chat,Média,Linxpos Manager,Linxpos Manager > Linxpos Manager Não Abre,SL27 - OSCAR FREIRE,Gabriel Mariano,TI | Suporte a Lojas,00:00:00,,,,,2025-04-08 09:33:41,,Não atribuído,,Linxpos Manager Não Abre,TI,Suporte a Lojas,Fechado,0,inbrands.com.br
26745,67,gerente.s27@inbrands.com.br,LINXPOS NÃO ESTÁ PASSANDO VENDA,FECHADO,Incidente,Formcreator,Alta,Linxpos,Linxpos > Erro Ao Finalizar Venda,SL27 - OSCAR FREIRE,Gabriel Mariano,TI | Suporte a Lojas,Não atribuído,,,,,2025-04-08 09:31:10,,Vencido,00:30,Erro Ao Finalizar Venda,TI,Suporte a Lojas,Fechado,0,inbrands.com.br

In [38]:
D_REQUERENTE = (
        df[['email_requerente', 'dominio_email']]
        .drop_duplicates()
        .sort_values(by='email_requerente')
        .reset_index(drop=True)
)
D_REQUERENTE['requerente_sk'] = D_REQUERENTE.index + 1
D_REQUERENTE

                    email_requerente    dominio_email  requerente_sk
0                                       Não atribuído              1
1                       Breno Maciel    Não atribuído              2
2                   Felipe Gonçalves    Não atribuído              3
3                     Gabriele Bispo    Não atribuído              4
4                  Jefferson Barbosa    Não atribuído              5
..                               ...              ...            ...
968   yellen.moreira@inbrands.com.br  inbrands.com.br            969
969      ygor.parecy@inbrands.com.br  inbrands.com.br            970
970  yngrid.ferreira@inbrands.com.br  inbrands.com.br            971
971        yuki.sato@inbrands.com.br  inbrands.com.br            972
972      yuri.santos@inbrands.com.br  inbrands.com.br            973

[973 rows x 3 columns]

In [39]:
# Criação da Tabela fato

F_CHAMADOS = df.merge(
    D_TECNICO,
    how='left',
    left_on=['nome_tecnico', 'departamento'],
    right_on=['nome_tecnico', 'departamento']
)

F_CHAMADOS = F_CHAMADOS.merge(
    D_CATEGORIA,
    how='left',
    left_on=['categoria', 'subcategoria'],
    right_on=['categoria', 'subcategoria']
)

F_CHAMADOS = F_CHAMADOS.merge(
    D_STATUS,
    how='left',
    left_on=['status','status_macro'],
    right_on=['status','status_macro']
)

F_CHAMADOS = F_CHAMADOS.merge(
    D_REQUERENTE,
    how='left',
    left_on=['email_requerente', 'dominio_email'],
    right_on=['email_requerente', 'dominio_email']
)

F_CHAMADOS = F_CHAMADOS.drop(columns=
                             ['nome_tecnico', 
                              'grupo',
                              'departamento', 
                              'categoria', 
                              'categoria', 
                              'subcategoria', 
                              'titulo',  
                              'status_macro',
                              'email_requerente',]
                              )
F_CHAMADOS = F_CHAMADOS.rename(columns={'id': 'id_chamado'})
F_CHAMADOS['chamado_sk'] = F_CHAMADOS.index + 1
F_CHAMADOS

,id_chamado,status,tipo,origem_abertura,prioridade,categoria_completa,localizacao,tempo_chamado,data_criacao,ultima_atualizacao,tempo_atribuicao,tempo_solucao,data_solucao,data_fechamento,expirado,tempo_resposta,grupo_descricao,flag_sem_tecnico,dominio_email,tecnico_sk,categoria_sk,status_sk,requerente_sk,chamado_sk
0,27299,EM ATENDIMENTO (ATRIBUÍDO),Requisição,Formcreator,Alta,Férias > Programação De Férias > Férias Fora Do Prazo,CD EMBU,Não atribuído,,,,,Não atribuído,,No prazo,,NaN,0,inbrands.com.br,1,253,1,631,1
1,27298,EM ATENDIMENTO (ATRIBUÍDO),Requisição,Formcreator,Média,Ponto Eletrônico > Manutenção De Ponto > Ajuste De Marcação,HUB-SP - CENESP BL C,Não atribuído,,,,,Não atribuído,,No prazo,,NaN,0,inbrands.com.br,1,421,1,522,2
2,27297,EM ATENDIMENTO (ATRIBUÍDO),Requisição,Formcreator,Média,Rescisão > Rescisão > Prévia De Rescisão,CD EMBU,Não atribuído,,,,,Não atribuído,,No prazo,,NaN,0,inbrands.com.br,35,453,1,468,3
3,27296,EM ATENDIMENTO (ATRIBUÍDO),Requisição,Formcreator,Média,Rescisão > Rescisão > Prévia De Rescisão,CD EMBU,Não atribuído,,,,,Não atribuído,,No prazo,,NaN,0,inbrands.com.br,35,453,1,468,4
4,27295,EM ATENDIMENTO (ATRIBUÍDO),Requisição,Formcreator,Média,Rescisão > Rescisão > Prévia De Rescisão,CD EMBU,Não atribuído,,,,,Não atribuído,,No prazo,,NaN,0,inbrands.com.br,35,453,1,468,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
26741,71,FECHADO,Requisição,Formcreator,Baixa,Fiscal > Reprocessamento De Notas Fiscais,LOJAS,Não atribuído,,,,,2025-04-08 18:59:35,,Vencido,02:00,Suporte a Lojas,0,inbrands.com.br,60,221,3,819,26742
26742,70,FECHADO,Requisição,Formcreator,Baixa,Fiscal > Reprocessamento De Notas Fiscais,LOJAS,Não atribuído,,,,,2025-04-08 18:58:27,,Vencido,02:00,Suporte a Lojas,0,inbrands.com.br,60,221,3,819,26743
26743,69,FECHADO,Requisição,Formcreator,Muito baixa,Não Atribuído,LOJAS,Não atribuído,,,,,2025-04-10 18:41:44,,Vencido,03:00,Suporte a Lojas,0,inbrands.com.br,60,361,3,820,26744
26744,68,FECHADO,Incidente,Chat,Média,Linxpos Manager > Linxpos Manager Não Abre,SL27 - OSCAR FREIRE,00:00:00,,,,,2025-04-08 09:33:41,,Não atribuído,,Suporte a Lojas,0,inbrands.com.br,32,327,3,392,26745
26745,67,FECHADO,Incidente,Formcreator,Alta,Linxpos > Erro Ao Finalizar Venda,SL27 - OSCAR FREIRE,Não atribuído,,,,,2025-04-08 09:31:10,,Vencido,00:30,Suporte a Lojas,0,inbrands.com.br,32,314,3,392,26746

In [41]:
# Criar arquivos excel

with pd.ExcelWriter("Tratamento_chamados.xlsx") as writer:
    D_TECNICO.to_excel(writer, sheet_name="D_TECNICO", index=False)
    D_CATEGORIA.to_excel(writer, sheet_name="D_CATEGORIA", index=False)
    D_STATUS.to_excel(writer, sheet_name="D_STATUS", index=False)
    D_REQUERENTE.to_excel(writer, sheet_name="D_REQUERENTE", index=False)
    F_CHAMADOS.to_excel(writer, sheet_name="F_CHAMADOS", index=False)